- markdown: |
    Hey @tasleson, a file(s) you own were modified in this PR! Could you take a look?
  pathFilter:
    - 'src/lib/ses*'
    - 'src/lib/smp*'

- markdown: |
    Hey @nfont, a file(s) you own were modified in this PR! Could you take a look?
  pathFilter:
    - 'src/lib/amd*'

- markdown: |
    Hey @prabhakar, a file(s) you own were modified in this PR! Could you take a look?
  pathFilter:
    - 'src/lib/dell*'
