name: Changelog
on:
  release:
    types:
      - created
jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: "Generate release changelog"
        uses: heinrichreimer/action-github-changelog-generator@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          releaseBranch: main
          output: "release_changelog.md"
          breakingLabel: breaks
          enhancementLabel: enhancement
          bugLabel: fixes
          removedLabel: removed